---
dist: xenial
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/manager
  matrix:
    - VERSION=latest VERSION_AWX=latest RELEASE_CEPH=nautilus RELEASE_OPENSTACK=train

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
