---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/manager
  matrix:
    - VERSION=nautilus-train VERSION_AWX=latest RELEASE_CEPH=nautilus RELEASE_OPENSTACK=train RELEASE_OSISM=latest

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
