---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Wait for the AWX API
      uri:
        url: "http://localhost:8052/api/v2/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Create default organization
      tower_organization:
        name: default

    - name: Create default inventory
      tower_inventory:
        name: default
        organization: default

    - name: Create configuration project
      tower_project:
        name: configuration
        organization: default
        scm_type: git
        scm_url: file:///opt/configuration
        scm_update_on_launch: true
        custom_virtualenv: /var/lib/awx/venv/osism

    - name: Add source to default inventory
      tower_inventory_source:
        inventory: default
        name: configuration
        overwrite: true
        overwrite_vars: true
        source: scm
        source_project: configuration
        source_path: inventory/hosts
        update_on_project_update: true

    - name: Create projects
      tower_project:
        name: "{{ item.name }}"
        organization: default
        scm_type: manual
        local_path: "{{ item.name }}"
        custom_virtualenv: "/var/lib/awx/venv/{{ item.virtualenv }}"
      with_items:
        - name: ceph
          virtualenv: ceph
        - name: osism
          virtualenv: osism
        - name: kolla
          virtualenv: kolla

    - name: Create vault credential
      tower_credential:
        name: vault
        organization: default
        kind: vault
        vault_password: password

    - name: Create ssh credential
      tower_credential:
        name: ssh
        organization: default
        kind: ssh

    # NOTE: it is not possible to set the used username with the tower_credential module
    - name: Set username/key for ssh credential
      shell: |
        tower-cli credential modify --name ssh --inputs '{ "username": "dragon", "ssh_key_data": "{{ lookup('file', '/ansible/secrets/id_rsa.operator') }}" }'

    - name: Create job templates
      tower_job_template:
        name: "{{ item.name|upper }}"
        project: "{{ item.project }}"
        inventory: default
        job_type: run
        playbook: awx.yml
        credential: ssh
        fact_caching_enabled: true
        survey_enabled: true
        survey_spec: "{{ lookup('file', '/var/lib/awx/surveys/' + item.survey + '.json') }}"
      with_items:
        - name: ceph
          project: ceph
          survey: ceph
        - name: osism
          project: osism
          survey: osism
        - name: kolla
          project: kolla
          survey: kolla
