---
- hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - awx.awx

  vars:
    workflows:
      - testbed-ceph
      - testbed-kolla-base

    ceph_roles:
      - clients
      - dashboard
      - facts
      - fetch-keys
      - iscsigws
      - mdss
      - mgrs
      - mons
      - nfss
      - osds
      - rbd-mirrors
      - restapis
      - rgws
      - rolling_update

    generic_roles:
      - auditd
      - chrony
      - cockpit
      - common
      - configuration
      - docker
      - docker-compose
      - facts
      - grub
      - hardening
      - hostname
      - hosts
      - network
      - operator
      - osquery
      - patchman-client
      - proxy
      - python
      - python3
      - repository
      - resolvconf
      - rsyslog
      - sosreport
      - sysdig
      - timezone
      - utilities

    infrastructure_roles:
      - cephclient
      - helper
      - openstackclient
      - patchman
      - pulp

    monitoring_roles:
      - netdata
      - zabbix
      - zabbix-agent

    kolla_roles:
      - aodh
      - barbican
      - ceilometer
      - cinder
      - cloudkitty
      - common
      - designate
      - elasticsearch
      - etcd
      - facts
      - glance
      - gnocchi
      - grafana
      - haproxy
      - heat
      - horizon
      - influxdb
      - iscsi
      - keystone
      - kibana
      - kuryr
      - magnum
      - manila
      - mariadb
      - memcached
      - mistral
      - multipathd
      - neutron
      - nova
      - octavia
      - openvswitch
      - panko
      - placement
      - rabbitmq
      - rally
      - redis
      - skydive
      - watcher
      - zun

  tasks:
    - name: Wait for the AWX API
      uri:
        url: "http://localhost:8052/api/v2/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 10

    - name: Create default organization
      tower_organization:
        name: default

    - name: Create default inventory
      tower_inventory:
        name: default
        organization: default

    - name: Create configuration project
      tower_project:
        name: configuration
        organization: default
        scm_type: git
        scm_url: file:///opt/configuration
        scm_update_on_launch: true
        custom_virtualenv: /var/lib/awx/venv/osism

    - name: Add source to default inventory
      tower_inventory_source:
        inventory: default
        name: configuration
        overwrite: true
        overwrite_vars: true
        source: scm
        source_project: configuration
        source_path: inventory/hosts
        update_on_project_update: true

    - name: Create projects
      tower_project:
        name: "{{ item.name }}"
        organization: default
        scm_type: manual
        local_path: "{{ item.name }}"
        custom_virtualenv: "/var/lib/awx/venv/{{ item.virtualenv }}"
      with_items:
        - name: ceph
          virtualenv: ceph
        - name: custom
          virtualenv: osism
        - name: generic
          virtualenv: osism
        - name: infrastructure
          virtualenv: osism
        - name: kolla
          virtualenv: kolla
        - name: monitoring
          virtualenv: osism
        - name: openstack
          virtualenv: osism

    # NOTE: it is not possible to set the used username with the tower_credential module
    #
    #       https://github.com/ansible/tower-cli/issues/452
    - name: Set username/key for ssh credential
      shell: |
        cat <<EOF > /tmp/cred.yaml
        ---
        username: dragon
        ssh_key_data: |
        $(awk '{printf "      %s\n", $0}' < /ansible/secrets/id_rsa.operator)
        EOF
        awx-cli credential create --name="operator" --credential-type="Machine" --organization="default" --inputs=@/tmp/cred.yaml
        rm -f /tmp/cred.yaml

    - name: Create generic job templates - type run
      tower_job_template:
        name: "{{ item.name|upper }}"
        project: "{{ item.project }}"
        inventory: default
        job_type: run
        playbook: awx.yml
        credential: operator
        fact_caching_enabled: true
        survey_enabled: true
        survey_spec: "{{ lookup('file', '/var/lib/awx/surveys/' + item.survey + '.json') }}"
      with_items:
        - name: ceph
          project: ceph
          survey: playbook
        - name: custom
          project: custom
          survey: playbook
        - name: generic
          project: generic
          survey: playbook
        - name: infrastructure
          project: infrastructure
          survey: playbook
        - name: kolla
          project: kolla
          survey: kolla
        - name: monitoring
          project: monitoring
          survey: playbook
        - name: openstack
          project: openstack
          survey: playbook

    - name: Create generic job templates - type check
      tower_job_template:
        name: "{{ item.name|upper }} - Check"
        project: "{{ item.project }}"
        inventory: default
        job_type: check
        playbook: awx.yml
        credential: operator
        fact_caching_enabled: true
        survey_enabled: true
        survey_spec: "{{ lookup('file', '/var/lib/awx/surveys/' + item.survey + '.json') }}"
      with_items:
        - name: ceph
          project: ceph
          survey: playbook
        - name: custom
          project: custom
          survey: playbook
        - name: generic
          project: generic
          survey: playbook
        - name: infrastructure
          project: infrastructure
          survey: playbook
        - name: kolla
          project: kolla
          survey: kolla
        - name: monitoring
          project: monitoring
          survey: playbook
        - name: openstack
          project: openstack
          survey: playbook

    - name: Create ceph job templates - type run
      tower_job_template:
        name: "Ceph - {{ item }}"
        project: ceph
        inventory: default
        job_type: run
        playbook: "ceph-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ ceph_roles }}"

    - name: Create ceph job templates - type check
      tower_job_template:
        name: "Ceph - {{ item }} - Check"
        project: ceph
        inventory: default
        job_type: check
        playbook: "ceph-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ ceph_roles }}"

    - name: Create generic job templates - type run
      tower_job_template:
        name: "Generic - {{ item }}"
        project: generic
        inventory: default
        job_type: run
        playbook: "generic-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ generic_roles }}"

    - name: Create generic job templates - type check
      tower_job_template:
        name: "Generic - {{ item }} - Check"
        project: generic
        inventory: default
        job_type: check
        playbook: "generic-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ generic_roles }}"

    - name: Create infrastructure job templates - type run
      tower_job_template:
        name: "Infrastructure - {{ item }}"
        project: infrastructure
        inventory: default
        job_type: run
        playbook: "infrastructure-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ infrastructure_roles }}"

    - name: Create infrastructure job templates - type check
      tower_job_template:
        name: "Infrastructure - {{ item }} - Check"
        project: infrastructure
        inventory: default
        job_type: check
        playbook: "infrastructure-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ infrastructure_roles }}"

    - name: Create monitoring job templates - type run
      tower_job_template:
        name: "Monitoring - {{ item }}"
        project: monitoring
        inventory: default
        job_type: run
        playbook: "monitoring-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ monitoring_roles }}"

    - name: Create monitoring job templates - type check
      tower_job_template:
        name: "Monitoring - {{ item }} - Check"
        project: monitoring
        inventory: default
        job_type: check
        playbook: "monitoring-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
      loop: "{{ monitoring_roles }}"

    - name: Create kolla job templates - type run
      tower_job_template:
        name: "Kolla - {{ item }}"
        project: kolla
        inventory: default
        job_type: run
        playbook: "kolla-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
        survey_enabled: true
        survey_spec: "{{ lookup('file', '/var/lib/awx/surveys/kolla-action.json') }}"
      loop: "{{ kolla_roles }}"

    - name: Create kolla job templates - type check
      tower_job_template:
        name: "Kolla - {{ item }} - Check"
        project: kolla
        inventory: default
        job_type: check
        playbook: "kolla-{{ item }}.yml"
        credential: operator
        fact_caching_enabled: true
        survey_enabled: true
        survey_spec: "{{ lookup('file', '/var/lib/awx/surveys/kolla-action.json') }}"
      loop: "{{ kolla_roles }}"
